### ISSUE TITLE
Face recognition

### ISSUE THREAD

**Issue by agalvezcorell** [Jorge-Doncel/Song-for-your-mood#2]
Echa un ojo al workshop de Marc para trabajar en la imagen input. 
Tienes que reconocer la cara, recortar la imagen, y pasar la imagen al tamaño adecuado para pasárselo al modelo.
https://github.com/boyander/machine-learning/tree/master/4-supervised-learning-face-recognition

**Comment by Jorge-Doncel** [comment]
Realizado¡ Ahora toca entrenar el modelo

![image](https://user-images.githubusercontent.com/65397130/88312273-3c1f2180-cd12-11ea-8c59-519e301dca6a.png)
