### ISSUE TITLE
Api - Flask

### ISSUE THREAD

**Issue by agalvezcorell** [Jorge-Doncel/Song-for-your-mood#4]
Ve preparando la api. 
No sé si te servirá, pero mi compañero Fer hizo una API en la que había un botón y le pasabas un audio. Te puede servir algo de la estructura o echarle un ojo para saber cómo hacer que, en tu caso, al darle a un botón suba una foto 🚀 
https://github.com/breogann/Final-project.Neural-network-tells-accents-apart

**Comment by Jorge-Doncel** [comment]
Muchas gracias porque llevo toda la mañana con ello y creo que lo he conseguido. No se me guarda en el ordenador la foto pero eso me da algo igual porque lo pasaré directamente a un array. Miro lo de Fer
