### ISSUE TITLE
[feedback - felipe]

### ISSUE THREAD

**Issue by ferrero-felipe** [Jorge-Doncel/Song-for-your-mood#5]
Muy buen trabajo, Jorge!
No solo con la red neuronal que funciona bastante bien, pero también con la api, que está muy guay!
Enhorabuena

![image](https://user-images.githubusercontent.com/52798316/89021974-9d05b580-d321-11ea-91fd-2d2231defe22.png)

**Comment by Jorge-Doncel** [comment]
Muchas gracias Felipe¡ Y gracias por estos dos meses por todas las veces que me has ayudado. Seguiré trabajando para un día poder hacer las katas tan bien como tú hehe Un abrazo¡
