### ISSUE TITLE
[feedback-ras]

### ISSUE THREAD

**Issue by olmocorell** [Jorge-Doncel/Song-for-your-mood#6]
Ha sido un verdadero gusto trabajar contigo, ya te lo he dicho en el zoom y por slack.
Siempre con ánimo para seguir mejorando y trabajando.
Ánimo con tus siguientes steps.

**Comment by Jorge-Doncel** [comment]
Muchísimas gracias ras¡ Ha sido un placer trabajar contigo. No dudes en contactarme si en el futuro alguno de los alumnos necesita algo o para lo que sea. Te agradezco mucho estos dos meses y te deseo lo mejor.
Un beso enorme
