### ISSUE TITLE
[feedback-marc]

### ISSUE THREAD

**Issue by boyander** [Jorge-Doncel/Song-for-your-mood#7]
Jorge, ehorabuena!!

No solo has entrenado un modelo de reconocimiento de sentimiento facial, si no que además le has dado caña a spotify analizando las letras para fusionar ambas cosas.

Muy buen proyecto, me ha gustado mucho. Creo que no me equivoco si digo que te esperan grandes momentos en #machinelearning. Pero se seguro que das la talla!!

Abrazotee!!

MP

![](https://laughingsquid.com/wp-content/uploads/emotion-gif.gif)

**Comment by Jorge-Doncel** [comment]
Muchas gracias marc¡ Me alegro que te haya gustado el proyecto, aunque tengo ideas de como poder mejorarlo e intentaré perfeccionarlo. 

Un abrazo y gracias por estos dos meses :)
